### ISSUE TITLE
Got "Cannot read property 'pkg' of null" when deploying

### ISSUE THREAD

**Issue by paulx3** [marbemac/dayjot#25]
Hi, I got "Cannot read property 'pkg' of null" when I deploy this app on my ubuntu 14 lts cloud. Can you help me . Thanks
```
Cannot read property 'pkg' of null
TypeError: Cannot read property 'pkg' of null
    at Function.Addon.resolvePath (/home/ubuntu/dayjot/ember/node_modules/ember-cli/lib/models/addon.js:318:18)
    at Function.Addon.lookup (/home/ubuntu/dayjot/ember/node_modules/ember-cli/lib/models/addon.js:333:22)
    at /home/ubuntu/dayjot/ember/node_modules/ember-cli/lib/models/project.js:204:34
    at visit (/home/ubuntu/dayjot/ember/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
    at DAG.topsort (/home/ubuntu/dayjot/ember/node_modules/ember-cli/lib/utilities/DAG.js:82:7)
    at Project.initializeAddons (/home/ubuntu/dayjot/ember/node_modules/ember-cli/lib/models/project.js:202:9)
    at Project.eachAddonCommand (/home/ubuntu/dayjot/ember/node_modules/ember-cli/lib/models/project.js:229:10)
    at module.exports (/home/ubuntu/dayjot/ember/node_modules/ember-cli/lib/cli/lookup-command.js:52:13)
    at CLI.<anonymous> (/home/ubuntu/dayjot/ember/node_modules/ember-cli/lib/cli/cli.js:31:26)
    at $$$internal$$tryCatch (/home/ubuntu/dayjot/ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:470:16)
```

**Comment by sergiy17** [comment]
Hi, any update on this issue?
